### ISSUE TITLE
crash when converting 2 converted bezier circle

### ISSUE THREAD

**Issue by mirlip** [mauge123/mechanical-blender#5]
in default scene, add a bezier circle, duplicate it, select both, alt+C to convert to mesh, ctrl+J to join, blender crashes with access violation. It doesn't happen on official 2.77.

**Comment by mauge123** [comment]
Commited 66b2cc18651166da513d7f6b37b10039896aec4c

It should be fixed

**Comment by mirlip** [comment]
Thank you :)

**Comment by mirlip** [comment]
actually it still crashes on windows : Error: EXCEPTION_ACCESS_VIOLATION
