### ISSUE TITLE
undo crashes with access violation if factory defaults are not restored

### ISSUE THREAD

**Issue by mirlip** [mauge123/mechanical-blender#6]
On windows, duplicate default cube, hit ctrl+Z -> blender crash. 
It doesn't happen on official 2.77 with same configuration and addons (so it's not caused by the addons or configuration). However, restoring factory defaults on this build resolves the problem.

**Comment by mauge123** [comment]
Cannot reproduce it...

**Comment by mauge123** [comment]
Also,  opened oficial 2.77, saved a scene with a cube. Opened with mechanical blender, cannot reproduce the crash.

**Comment by mirlip** [comment]
I'll try to find the addon causing the crash. Thing is, this addon only crash on mechanical Blender and not official 2.77. So it may be due to some changes in this branch. I'll keep you informed as soon as I can.

**Comment by mirlip** [comment]
--------------------------------------
Posted this message in wrong issue thread for some reason. sorry :/ I repost it here to make it more clear.
-----------------------------------------
Ok, found it. It's not due to an addon as it happens with factory defaults.

   1. On default scene, duplicate the cube

    2. join both copies

    3. then undo with ctrl+Z.

    4. Now go try to go to the material panel, it crashes blender with access violation.

This bug doesn't happen in 2.77 official

**Comment by mauge123** [comment]
should be solved on 166aeb27f90502789755e8d9cc42fe8b20134e07 referring to issue #7

**Comment by mirlip** [comment]
After compiling latest commit, following steps above it still crashes with cycles. But not with BI renderer. Restoring default doesn't help.

**Comment by mauge123** [comment]
Should be solved with 89cdfa450ae47c8e465f0adf417c8a458633f13c

In fact, was crashing when rendering.

**Comment by mirlip** [comment]
Yep, it solved the problem :)
